name: open_route_example
description: A new Flutter project.
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  reactive_forms: ^10.6.2
  open_route_services:
    path: ../
  flutter_dotenv: ^5.0.2
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^1.0.0
  flutter_map_marker_popup: ^2.0.0
  #flutter_map_marker_cluster: ^0.4.2
  #flutter_map_tappable_polyline: ^3.1.0
  #flutter_map_tile_caching: ^3.0.2
  substring_highlight: ^1.0.33

  #map_launcher: ^2.1.1
  #map_picker: ^0.0.3
  #map: ^1.0.0
  autocomplete_field:
    git: https://github.com/mosamuhana/flutter_autocomplete_field.git
    #path: ../../../FLUTTER_AUTOCOMPLETE/flutter_autocomplete_field


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
